# Kingdom World © (Minecraft Plugin)
# By: Colin Okhuijzen Mulder ( ColleBol ) - contact@collebol.org
#
# Spigot-version: 1.21.5-R0.1-SNAPSHOT

# Color-pallet
text-color:
  default: "#66EE66"
  yellow: "#FFF777"
  error: "#FF4A4A"
  success: "#27FF27"
  gray: "#C1C1C1"